runno: '001'

feature_engineering:
  method_fillna: '-999'  # -999, forward

cv:
  name: KFold
  param:
    n_splits: 5
    shuffle: True

model:
  name: XGBClassifier
  model_param:
    n_estimators: 100
    max_depth: 11
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.7
    missing: -999
    random_state: 42
    tree_method: gpu_hist
  train_param:
    eval_metric: logloss
    early_stopping_rounds: 5

target:
  path: processed/raw_pickle_v1/train.pkl
  col: Survived

info:
  path: null
  cols: null

features:
  - name: raw
    path: processed/raw_pickle_v1/train.pkl
    cols:
      - PassengerId
      - Pclass
      # - Name
      # - Sex
      - Age
      - SibSp
      - Parch
      # - Ticket
      - Fare
      # - Cabin
      # - Embarked

test:
  name: test
  path: processed/raw_pickle_v1/test.pkl
