mlflow:
  experiment:
    name: train_v1
    tags: 
      exec: prd  # dev, test, prd

out_dir: train_v1/prd001

option:
  train: true
  predict: true

feature_engineering:
  method_fillna: '-999'  # -999, forward

cv:
  name: nocv
  param:
    n_splits: 1

model:
  name: XGBClassifier
  model_param:
    n_estimators: 500
    max_depth: 11
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.7
    missing: -999
    random_state: 2020
    tree_method: gpu_hist
  train_param:
    eval_metric: null
    early_stopping_rounds: null

target:
  path: processed/raw_pickle_v1/train.pkl
  col: Survived

info:
  path: null
  cols: null

features:
  - name: raw
    path: processed/raw_pickle_v1/train.pkl
    cols:
      - PassengerId
      - Pclass
      # - Name
      # - Sex
      - Age
      - SibSp
      - Parch
      # - Ticket
      - Fare
      # - Cabin
      # - Embarked

test:
  name: test
  path: processed/raw_pickle_v1/test.pkl
