runno: '001'

feature_engineering:
  method_fillna: '-999'  # -999, forward

cv:
  name: KFold
  param:
    n_splits: 5
    shuffle: True

modelxgb:
  name: XGBClassifier
  model_param:
    n_estimators: 100
    max_depth: 11
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.7
    missing: -999
    random_state: 42
    tree_method: gpu_hist
  train_param:
    eval_metric: logloss
    early_stopping_rounds: 5

modellgb:
  name: LGBMClassifier
  model_param:
    boosting_type: gbdt
    num_leaves: 31
    max_depth: -1
    learning_rate: 0.1
    n_estimators: 100
    subsample_for_bin: 200000
    objective: null
    class_weight: null
    min_split_gain: 0.0
    min_child_weight: 0.001
    min_child_samples: 20
    subsample: 1.0
    subsample_freq: 0
    colsample_bytree: 1.0
    reg_alpha: 0.2
    reg_lambda: 0.0
    random_state: null
    n_jobs: -1
    silent: True
    importance_type: split
  train_param:
    eval_metric: logloss
    early_stopping_rounds: 5

model:
  name: CatBoostClassifier
  model_param:
    loss_function: Logloss
    eval_metric: Logloss
  train_param:
    early_stopping_rounds: 5

target:
  path: processed/raw_pickle_v1/train.pkl
  col: Survived

info:
  path: null
  cols: null

features:
  - name: raw
    path: processed/raw_pickle_v1/train.pkl
    cols:
      - PassengerId
      - Pclass
      # - Name
      # - Sex
      - Age
      - SibSp
      - Parch
      # - Ticket
      - Fare
      # - Cabin
      # - Embarked

test:
  name: test
  path: processed/raw_pickle_v1/test.pkl
